// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AuthToken is the predicate function for authtoken builders.
type AuthToken func(*sql.Selector)

// Category is the predicate function for category builders.
type Category func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// Vendor is the predicate function for vendor builders.
type Vendor func(*sql.Selector)
