// Code generated by ent, DO NOT EDIT.

package category

import (
	"handl-server/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Category {
	return predicate.Category(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Category {
	return predicate.Category(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Category {
	return predicate.Category(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Category {
	return predicate.Category(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Category {
	return predicate.Category(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Category {
	return predicate.Category(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Category {
	return predicate.Category(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Category {
	return predicate.Category(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Category {
	return predicate.Category(sql.FieldLTE(FieldID, id))
}

// Category applies equality check predicate on the "category" field. It's identical to CategoryEQ.
func Category(v string) predicate.Category {
	return predicate.Category(sql.FieldEQ(FieldCategory, v))
}

// Subcategory applies equality check predicate on the "subcategory" field. It's identical to SubcategoryEQ.
func Subcategory(v string) predicate.Category {
	return predicate.Category(sql.FieldEQ(FieldSubcategory, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Category {
	return predicate.Category(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Category {
	return predicate.Category(sql.FieldEQ(FieldUpdatedAt, v))
}

// CategoryEQ applies the EQ predicate on the "category" field.
func CategoryEQ(v string) predicate.Category {
	return predicate.Category(sql.FieldEQ(FieldCategory, v))
}

// CategoryNEQ applies the NEQ predicate on the "category" field.
func CategoryNEQ(v string) predicate.Category {
	return predicate.Category(sql.FieldNEQ(FieldCategory, v))
}

// CategoryIn applies the In predicate on the "category" field.
func CategoryIn(vs ...string) predicate.Category {
	return predicate.Category(sql.FieldIn(FieldCategory, vs...))
}

// CategoryNotIn applies the NotIn predicate on the "category" field.
func CategoryNotIn(vs ...string) predicate.Category {
	return predicate.Category(sql.FieldNotIn(FieldCategory, vs...))
}

// CategoryGT applies the GT predicate on the "category" field.
func CategoryGT(v string) predicate.Category {
	return predicate.Category(sql.FieldGT(FieldCategory, v))
}

// CategoryGTE applies the GTE predicate on the "category" field.
func CategoryGTE(v string) predicate.Category {
	return predicate.Category(sql.FieldGTE(FieldCategory, v))
}

// CategoryLT applies the LT predicate on the "category" field.
func CategoryLT(v string) predicate.Category {
	return predicate.Category(sql.FieldLT(FieldCategory, v))
}

// CategoryLTE applies the LTE predicate on the "category" field.
func CategoryLTE(v string) predicate.Category {
	return predicate.Category(sql.FieldLTE(FieldCategory, v))
}

// CategoryContains applies the Contains predicate on the "category" field.
func CategoryContains(v string) predicate.Category {
	return predicate.Category(sql.FieldContains(FieldCategory, v))
}

// CategoryHasPrefix applies the HasPrefix predicate on the "category" field.
func CategoryHasPrefix(v string) predicate.Category {
	return predicate.Category(sql.FieldHasPrefix(FieldCategory, v))
}

// CategoryHasSuffix applies the HasSuffix predicate on the "category" field.
func CategoryHasSuffix(v string) predicate.Category {
	return predicate.Category(sql.FieldHasSuffix(FieldCategory, v))
}

// CategoryIsNil applies the IsNil predicate on the "category" field.
func CategoryIsNil() predicate.Category {
	return predicate.Category(sql.FieldIsNull(FieldCategory))
}

// CategoryNotNil applies the NotNil predicate on the "category" field.
func CategoryNotNil() predicate.Category {
	return predicate.Category(sql.FieldNotNull(FieldCategory))
}

// CategoryEqualFold applies the EqualFold predicate on the "category" field.
func CategoryEqualFold(v string) predicate.Category {
	return predicate.Category(sql.FieldEqualFold(FieldCategory, v))
}

// CategoryContainsFold applies the ContainsFold predicate on the "category" field.
func CategoryContainsFold(v string) predicate.Category {
	return predicate.Category(sql.FieldContainsFold(FieldCategory, v))
}

// SubcategoryEQ applies the EQ predicate on the "subcategory" field.
func SubcategoryEQ(v string) predicate.Category {
	return predicate.Category(sql.FieldEQ(FieldSubcategory, v))
}

// SubcategoryNEQ applies the NEQ predicate on the "subcategory" field.
func SubcategoryNEQ(v string) predicate.Category {
	return predicate.Category(sql.FieldNEQ(FieldSubcategory, v))
}

// SubcategoryIn applies the In predicate on the "subcategory" field.
func SubcategoryIn(vs ...string) predicate.Category {
	return predicate.Category(sql.FieldIn(FieldSubcategory, vs...))
}

// SubcategoryNotIn applies the NotIn predicate on the "subcategory" field.
func SubcategoryNotIn(vs ...string) predicate.Category {
	return predicate.Category(sql.FieldNotIn(FieldSubcategory, vs...))
}

// SubcategoryGT applies the GT predicate on the "subcategory" field.
func SubcategoryGT(v string) predicate.Category {
	return predicate.Category(sql.FieldGT(FieldSubcategory, v))
}

// SubcategoryGTE applies the GTE predicate on the "subcategory" field.
func SubcategoryGTE(v string) predicate.Category {
	return predicate.Category(sql.FieldGTE(FieldSubcategory, v))
}

// SubcategoryLT applies the LT predicate on the "subcategory" field.
func SubcategoryLT(v string) predicate.Category {
	return predicate.Category(sql.FieldLT(FieldSubcategory, v))
}

// SubcategoryLTE applies the LTE predicate on the "subcategory" field.
func SubcategoryLTE(v string) predicate.Category {
	return predicate.Category(sql.FieldLTE(FieldSubcategory, v))
}

// SubcategoryContains applies the Contains predicate on the "subcategory" field.
func SubcategoryContains(v string) predicate.Category {
	return predicate.Category(sql.FieldContains(FieldSubcategory, v))
}

// SubcategoryHasPrefix applies the HasPrefix predicate on the "subcategory" field.
func SubcategoryHasPrefix(v string) predicate.Category {
	return predicate.Category(sql.FieldHasPrefix(FieldSubcategory, v))
}

// SubcategoryHasSuffix applies the HasSuffix predicate on the "subcategory" field.
func SubcategoryHasSuffix(v string) predicate.Category {
	return predicate.Category(sql.FieldHasSuffix(FieldSubcategory, v))
}

// SubcategoryIsNil applies the IsNil predicate on the "subcategory" field.
func SubcategoryIsNil() predicate.Category {
	return predicate.Category(sql.FieldIsNull(FieldSubcategory))
}

// SubcategoryNotNil applies the NotNil predicate on the "subcategory" field.
func SubcategoryNotNil() predicate.Category {
	return predicate.Category(sql.FieldNotNull(FieldSubcategory))
}

// SubcategoryEqualFold applies the EqualFold predicate on the "subcategory" field.
func SubcategoryEqualFold(v string) predicate.Category {
	return predicate.Category(sql.FieldEqualFold(FieldSubcategory, v))
}

// SubcategoryContainsFold applies the ContainsFold predicate on the "subcategory" field.
func SubcategoryContainsFold(v string) predicate.Category {
	return predicate.Category(sql.FieldContainsFold(FieldSubcategory, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Category {
	return predicate.Category(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Category {
	return predicate.Category(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Category {
	return predicate.Category(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Category {
	return predicate.Category(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Category {
	return predicate.Category(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Category {
	return predicate.Category(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Category {
	return predicate.Category(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Category {
	return predicate.Category(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Category {
	return predicate.Category(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Category {
	return predicate.Category(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Category {
	return predicate.Category(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Category {
	return predicate.Category(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Category {
	return predicate.Category(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Category {
	return predicate.Category(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Category {
	return predicate.Category(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Category {
	return predicate.Category(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Category) predicate.Category {
	return predicate.Category(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Category) predicate.Category {
	return predicate.Category(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Category) predicate.Category {
	return predicate.Category(sql.NotPredicates(p))
}
