import {DataTypes, QueryInterface} from "sequelize";
import {v4 as uuidv4} from "uuid";

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  // eslint-disable-next-line
  async up (queryInterface: QueryInterface, Sequelize: typeof DataTypes) {
    let data = [
      {
        "uuid": "",
        "name": "1 ST LH SUNGLASSES INC.",
        "description": "Wholesale sunglasses and sunglasses display www.glhsunglasses.com",
        "website": "http://www.glhsunglasses.com",
        "categories": "Sunglasses / Eyewear, General Merchandise, General Gifts",
        "people": ["Linda Li"],
        "address": "58-25 63RD STREET",
        "city": "Maspeth",
        "state": "NY",
        "zipcode": "11378",
        "phoneNumber": "(212)868-5656",
        "email": "info_1stlhsunglasses@yahoo.com",
        "createdAt": new Date(Date.now()),
        "updatedAt": new Date(Date.now()),
      },
      {
        "uuid": "",
        "name": "26 California Wholesale",
        "description": "26 California Wholesale has been one of the region's largest general merchandise importers and wholesalers. Decor, Kitchen, Pet, Garden, Party, Cleaning, Bath are some of our categories we supply for you including Bonita Home, Cali-Home, Promarx, Echols, Magic Cover and Con-Tact Brand products. We offer branded and non- branded goods at all incredible savings that translate to large profits for your company. Thank you for being the best part of 26 California Wholesale!",
        "website": "http://www.26CWS.com",
        "categories": "Baby / Kids Products, Dollar Store Items, General Gifts",
        "people": ["Lluis Portet", "Sandra Gomez"],
        "address": "2845 East 26th Street",
        "city": "Vernon",
        "state": "CA",
        "zipcode": "90058",
        "phoneNumber": "(323)588-3026",
        "email": "cs@26cws.com",
        "createdAt": new Date(Date.now()),
        "updatedAt": new Date(Date.now()),
      },
      {
        "uuid": "",
        "name": "2HOPE ACCESSORIES, INC",
        "description": "Fashion Jewelry and Accessories! We also carry fashion jewelry for kids, a variety of fun novelty items and cosmetics!",
        "website": "http://www.twohopeaccessories.com",
        "categories": "Fashion Jewelry / Watches, Cosmetics / Nails / Hair Products, General Gifts",
        "people": ["Sylvia Kim"],
        "address": "55 Tec St",
        "city": "Hicksville",
        "state": "NY",
        "zipcode": "11801",
        "phoneNumber": "(631) 396-0877",
        "email": "",
        "createdAt": new Date(Date.now()),
        "updatedAt": new Date(Date.now()),
      },
      {
        "uuid": "",
        "name": "306 Deep Dead Sea Products",
        "description": "Unleashing the Depths: The Power of the Dead Sea Waters.\nAt a staggering depth of 306 meters, the 306 Deep Dead Sea products brand echoes the untamed power that resides within the depths of the Dead Sea. As the exclusive distributor of Dead Sea raw materials in North America, we proudly stand as the fortress, relieving factories, labs, and all within the Dead Sea industry from the burdensome search for suppliers.\n306 Deep Dead Sea products, represents excellence and innovation in the industry. With unwavering dedication, we ensure uninterrupted access to the extraordinary Dead Sea raw materials, serving as the exclusive conduit for companies operating in Jordan.\nBy eliminating the complexities of sourcing and providing a seamless supply chain, we empower businesses across North America to unlock the true potential of the Dead Sea. Our products serve as a catalyst for innovation, enabling companies to create exceptional offerings that harness the unmatched benefits of this remarkable natural resource.\nThrough our extensive network and strategic partnerships, we guarantee reliable access to the Dead Sea raw materials, working closely with companies in Jordan. We take great pride in our role as the fortress, safeguarding the integrity and availability of these valuable resources.\nWith 306 Deep Dead Sea products brand, we stand as a beacon of reliability, trust, and unparalleled expertise in the North American market. Together, we can dive deep into the immense power of the Dead Sea and unlock a world of possibilities for businesses and consumers alike.",
        "website": "WWW.306DEEP.COM",
        "categories": "",
        "people": ["HIlal Rahal"],
        "address": "621 Consortium Court",
        "city": "London Ontario",
        "state": "N6E2S8, CA",
        "zipcode": "",
        "phoneNumber": "360-646-3360 ext 800",
        "email": "info@306deep.com",
        "createdAt": new Date(Date.now()),
        "updatedAt": new Date(Date.now()),
      },
      {
        "uuid": "",
        "name": "365 Fashions Inc.",
        "description": "365 Fashions Inc. is an experienced Importer & Wholesaler of Sunglasses and Reading Glasses. It is in New York wholesale district for years. Our unique design and impressive quality have been helped so many customers to improve the business. 365 Fashions team has strong desire to assist the customer. Please feel free to explore the new styles at booth# N24116. 365 Fashions Inc. look forward to a successful working relationship with you in the future!",
        "website": "http://www.365fashions.com",
        "categories": "Sunglasses / Eyewear, General Merchandise, General Gifts, Souvenirs",
        "people": ["Yvonne Jin"],
        "address": "1710 Flashing Ave Ste 16",
        "city": "Ridgewood",
        "state": "NY",
        "zipcode": "11385",
        "phoneNumber": "(718) 576-3369",
        "email": "365fashions@gmail.com",
        "createdAt": new Date(Date.now()),
        "updatedAt": new Date(Date.now()),
      },
      {
        "uuid": "",
        "name": "5D Global Distributions LLC",
        "description": "5D Global Distributions is a leading provider of comprehensive E-Commerce and Retail solutions tailored to businesses of all sizes. We specialize in offering a suite of services encompassing E-Commerce platform development, Retail, strategic marketing, streamlined supply chain management, and more. Our mission is to empower businesses to thrive in the dynamic online marketplace by providing innovative, scalable, and customizable solutions.",
        "website": "https://5dglobaldistributions.com/about-us-2/",
        "categories": "",
        "people": ["Monica Wells"],
        "address": "2917 Chalfont Ln",
        "city": "Plano",
        "state": "TX",
        "zipcode": "75023",
        "phoneNumber": "(972) 612-1222",
        "email": "www.globaladdistribution.com",
        "createdAt": new Date(Date.now()),
        "updatedAt": new Date(Date.now()),
      },
      {
        "uuid": "",
        "name": "7 Color Import Inc.",
        "description": "We carry trendy shoes, handbags, and accessories perfect for your stores!",
        "website": "http://www.7colorimport.com",
        "categories": "Handbags, Hats / Scarves, Women's Footwear",
        "people": ["Amy Lin"],
        "address": "1706 Flashing Ave",
        "city": "Queens",
        "state": "NY",
        "zipcode": "11385",
        "phoneNumber": "(347) 763-0627",
        "email": "amylincollection@gmail.com",
        "createdAt": new Date(Date.now()),
        "updatedAt": new Date(Date.now()),
      },
      {

        "uuid": "",
        "name": "7 STAR TRADING",
        "description": "Historically accurate chinese swords",
        "website": "www.sevenstarstrading.com",
        "categories": "General Merchandise",
        "people": ["Javid Sharifi"],
        "address": "3543 Marvin St",
        "city": "Annandale",
        "state": "VA",
        "zipcode": "22003",
        "phoneNumber": "(703) 573-2939",
        "email": "sevenstarstrading688@gmail.com",
        "createdAt": new Date(Date.now()),
        "updatedAt": new Date(Date.now()),
      },
      {
        "uuid": "",
        "name": "702AVE",
        "description": "Blank apparel wholesaler",
        "website": "https://702ave.com/",
        "categories": "Men's Apparel",
        "people": ["Huda Muwalla"],
        "address": "4685 Boulder Highway",
        "city": "Las Vegas",
        "state": "NV",
        "zipcode": "89121",
        "phoneNumber": "702-358-3882",
        "email": "N/A",
        "createdAt": new Date(Date.now()),
        "updatedAt": new Date(Date.now()),
      },
      {
        "uuid": "",
        "name": "79 South China Import",
        "description": "Wholesale Sandals, Slippers, Aqua Shoes, Boots, Flip Flops and Footwear for over 43 years. Please visit our booth for Show Specials and great New styles. Established in 1979 in New York our history shows our commitment in specializing in footwear for all our customers. Best Prices and Quality,New styles with Great ROI for your stores. We are a dependable footwear source that carries items in Stock and ship out the same/next business day. Please visit or website for www.southchinaimport.com and our booth for all our inventory.",
        "website": "http://www.southchinaimport.com",
        "categories": "Swimwear, Kids / Baby Footwear, Men's Footwear, Women's Footwear, Closeouts / Liquidation",
        "people": ["Samuel Wong", "Bobby Cheung"],
        "address": "28 Williams St",
        "city": "Lynbrook",
        "state": "NY",
        "zipcode": "11563",
        "phoneNumber": "718) 389-6731",
        "email": "sochinany@yahoo.com",
        "createdAt": new Date(Date.now()),
        "updatedAt": new Date(Date.now()),
      },
      {
        "uuid": "",
        "name": "8A Inc",
        "description": "8A INC\n \n CELLPHONE ACCESSORIES WHOLESALE\n \n China Manufacturer Direct price!\n \n Best value for your money!",
        "website": "http://www.8awholesale.com",
        "categories": "Cell Phone Accessories / Wearables / Headphones / Speakers, Toys / Figures",
        "people": ["Sunita Mahase"],
        "address": "5207 Flushing Ave",
        "city": "Maspeth",
        "state": "NY",
        "zipcode": "11378",
        "phoneNumber": "1-347-287-2517",
        "email": "K19561130@gmail.com",
        "createdAt": new Date(Date.now()),
        "updatedAt": new Date(Date.now()),
      },
      {
        "uuid": "",
        "name": "A & M Wholesale Group, LLC",
        "description": "A & M Wholesale Group is located at 1117-B East Center Street in Madisonville, Kentucky, and is an importer of a variety of our own trademarked brands. Our trademarked brands are Countryside Products, Totally Cool Toys, Kentucky Tactical Supply, Camco Tools, and Kentucky Cutlery Company. Our goal is to provide the best service with the lowest price. For more information about our company, feel free to contact us at: 270-821-7100.",
        "website": "http://aandmwholesalegroup.com",
        "categories": "General Merchandise, Interior Décor (Curtains/Wall Art/etc.), Characters / Brands / Entertainment, Personal Security / Tactical, Toys / Figures",
        "people": ["Mike Coke"],
        "address": "100 Memorial Dr",
        "city": "Hanson",
        "state": "KY",
        "zipcode": "42413",
        "phoneNumber": "(270) 821-7100",
        "email": "sales@aandmwholesalegroup.com",
        "createdAt": new Date(Date.now()),
        "updatedAt": new Date(Date.now()),
      },
      {
        "uuid": "",
        "name": "A-LINE GREETINGS",
        "description": "North America's value-priced leader since 1985. A-Line Greetings has helped customers celebrate life’s special moments with our unique offering of Everyday and Seasonal Greeting Cards, We create specific Planograms for individual needs and service merchandise for our accounts. Our team of talented designers, illustrators, and editorial staff work tirelessly to provide the perfect blend of fresh and innovative design with relevant sentiment under the Rosedale Gold, Rosedale, and Mill Brook Studio Brands. Everyday and Seasonal Gift Bags, Gift Wrap, Roll Wrap, Tissue, Bows, Announcements and Invitations, Bottle Bags, Social Stationery, 2-year Pocket Planners, Note Pads, Pen and Pad Sets, Journals, Lined Note Pads, Writing Pads, Magnetic Memo Pads, Desk Memo Pads, Hard Cover List Pads, Everyday and Seasonal Accessories, and all other Social stationery items. We are working with a",
        "website": "http://alinegreetings.com",
        "categories": "General Gifts, Stationery / Party / Paper / Gift Wrap, Christmas",
        "people": ["Peter Bourhas"],
        "address": "Corner Brook, Newfoundland, Canada",
        "city": "",
        "state": "",
        "zipcode": "",
        "phoneNumber": "800 790 1280",
        "email": "customerservice@ALineGreetings.com",
        "createdAt": new Date(Date.now()),
        "updatedAt": new Date(Date.now()),
      },
      {
        "uuid": "",
        "name": "A1 Wholesale Inc.",
        "description": "Security fence wholesaler",
        "website": "a1wholesalefence.com",
        "categories": "",
        "people": ["Ali Ravjani"],
        "address": "15151 7th Ave",
        "city": "Whitestone",
        "state": "NY",
        "zipcode": "11357",
        "phoneNumber": "(718) 767-9800",
        "email": "A1WholesaleFence@gmail.com",
        "createdAt": new Date(Date.now()),
        "updatedAt": new Date(Date.now()),
      },
      {
        "uuid": "",
        "name": "AAA International",
        "description": "Leaders in LCD and Quartz Watches. For over 30 years distributiors of Q&Q Watches made by Citizen.",
        "website": "http://www.aaala.net",
        "categories": "Fashion Jewelry / Watches, General Gifts",
        "people": ["Amin Lalani"],
        "address": "",
        "city": "",
        "state": "",
        "zipcode": "",
        "phoneNumber": "",
        "email": "",
        "createdAt": new Date(Date.now()),
        "updatedAt": new Date(Date.now()),
      },
      {
        "uuid": "",
        "name": "AAB Style, Inc.",
        "description": "We've been in the market for more than 25 years and we are one of the world’s first and leading manufacturers of Stainless Steel. We have a rich history of innovation and growth as a true industry leader. We only use high quality materials such as, 316L Surgical Steel, Stainless Steel and Tungsten. We offer great package deals for you to take advantage of, come and enjoy the experience and savings!",
        "website": "http://www.aabstyle.com",
        "categories": "Fashion Jewelry / Watches, Body Piercings",
        "people": ["Dror Yakovpour", "Ana Yakovpour"],
        "address": "6851 W Sunrise Blvd Ste 170",
        "city": "Plantation",
        "state": "FL",
        "zipcode": "33313",
        "phoneNumber": "(954)-327-4262",
        "email": "info@aabstyle.com",
        "createdAt": new Date(Date.now()),
        "updatedAt": new Date(Date.now()),
      },
      {
        "uuid": "",
        "name": "Aaron USA LLC",
        "description": "Vivicreate brand belong to Aaron USA LLC company. Aaron USA LLC has own factory in China directly. Manufacture Gas Stove, Outdoor Stove, Patio Heater, S/S Comal, S/S Cazo, and Non Stick Pan. Specially in Cast Iron items, since 1980.",
        "website": "http://www.usaaron.com",
        "categories": "Kitchen / Tabletop / Cookware / Cutlery / Small Appliances, Outdoor Living / Décor, Hardware / Tools, Camping / Outdoor Recreation",
        "people": ["Aaron Hu"],
        "address": "980 Monterey Pass Rd",
        "city": "Monterey Park",
        "state": "CA",
        "zipcode": "91754",
        "phoneNumber": "626-879-7272",
        "email": "sales@usaaron.com",
        "createdAt": new Date(Date.now()),
        "updatedAt": new Date(Date.now()),
      },
      {
        "uuid": "",
        "name": "ABC 123 Accessories",
        "description": "At ABC 123 Accessories we carry a complete line of Travel-Size Convenience, Health & Beauty Items & Travel Accessories. Fanny Packs, Crossbody Messenger Bags, Backpacks & Wallets. We also have a full line of Cellular Accessories Chargers, Adaptors, Blocks & Power Banks. We do Custom Embroidery, Screen Printing & Heat Transfers for T-Shirts, Polos, Sweatshirts & Hoodies. Sizes range from Infant, 1zees to Adult Sizes to 5X",
        "website": "http://www.abc123accessories.com",
        "categories": "Small Leather Goods (Belts/Wallets/etc), Kids / Baby Apparel, Men's Apparel, Women's Apparel, Wellness / Personal Care",
        "people": ["A.J. Manghnani"],
        "address": "1805 Acme Street",
        "city": "Orlando",
        "state": "FL",
        "zipcode": "32805",
        "phoneNumber": "(407) 226-7272",
        "email": "abclowprices@gmail.com",
        "createdAt": new Date(Date.now()),
        "updatedAt": new Date(Date.now()),
      },
      {
        "uuid": "",
        "name": "ABC Trading",
        "description": "ABC Trading-Importers Wholesale",
        "website": "http://abctradinginc.com",
        "categories": "General Gifts, Novelties (Humor/Gags & Pranks/Drinking Accessories/etc), Plush, Toys / Figures",
        "people": ["Chan Hong Luo"],
        "address": "2100 E. 25th St.",
        "city": "Vernon",
        "state": "CA",
        "zipcode": "90058",
        "phoneNumber": "(323) 581-3688",
        "email": "abctradingabc@gmail.com",
        "createdAt": new Date(Date.now()),
        "updatedAt": new Date(Date.now()),
      },
      {
        "uuid": "",
        "name": "Abraham Lichaa Co LLC",
        "description": "We are based in Providence, Rhode Island and have been manufacturing in the United States since 1965 and also importing since 2005. We offer a large selection of earrings, necklaces and bracelets in Genuine European Crystal, Cubic Zirconia and freshwater pearls. We also offer counter top display units as well as individual styles designed for quick and easy sale. We look forward to working with you!",
        "website": "http://www.abrahamlichaaco.com",
        "categories": "Fashion Jewelry / Watches, General Merchandise, Wedding / Bridal, Made in the USA, Christmas",
        "people": ["Jacob Lichaa"],
        "address": "30 Virginia Ave",
        "city": "Providence",
        "state": "RI",
        "zipcode": "02905",
        "phoneNumber": "(401) 461-1116",
        "email": "Jacob@AbrahamLichaaCo.com",
        "createdAt": new Date(Date.now()),
        "updatedAt": new Date(Date.now()),
      },
      {
        "uuid": "",
        "name": "Abysse America",
        "description": "Licensed Merchandise and collectibles for Movies, Animes, Mangas, Comics including One Piece, DBZ, Naruto, My Hero Academia, The Seven Deadly Sins, Chi, Harry Potter, DC Comics, and Lord of the Rings.\n\nAbysse America develops and manufactures high quality, licensed merchandise for anime, manga, comics and movie enthusiasts.\n\nRanging from drinkware and keychains to apparel, plush and toys, our innovative products are driven by pop-culture trends and made with fans in mind!",
        "website": "http://www.abysse-america.com/",
        "categories": "General Gifts, Characters / Brands / Entertainment, Toys / Figures",
        "people": ["Dani Chiong"],
        "address": "15002 NW 107th Ave Ste 2",
        "city": "Hialeah",
        "state": "FL",
        "zipcode": "33018",
        "phoneNumber": "(305) 392-0178",
        "email": "contact@abysse-america.com",
        "createdAt": new Date(Date.now()),
        "updatedAt": new Date(Date.now()),
      },
      {
        "uuid": "",
        "name": "ACE Gifts Inc",
        "description": "",
        "website": "https://wooddesignice.com",
        "categories": "",
        "people": ["Ryan Trang"],
        "address": "",
        "city": "",
        "state": "",
        "zipcode": "",
        "phoneNumber": "",
        "email": "",
        "createdAt": new Date(Date.now()),
        "updatedAt": new Date(Date.now()),
      },
      {
        "uuid": "",
        "name": "Ace Watches Inc.",
        "description": "We specialize in manufacturing, importing, and distributing fast fashion and affordable accessories within the global watches and jewelry market. With a focus on younger, trendsetting audiences, we stay connected to the constantly changing market trends. Our products are distributed worldwide, catering to a wide variety of audiences. We have something for everyone!",
        "website": "http://www.acewatcheswholesale.com",
        "categories": "Fashion Jewelry / Watches",
        "people": ["Vicky Lakhati"],
        "address": "1330 Westheimer Rd",
        "city": "Houston",
        "state": "TX",
        "zipcode": "77042",
        "phoneNumber": "713-521-4444",
        "email": "",
        "createdAt": new Date(Date.now()),
        "updatedAt": new Date(Date.now()),
      },
      {
        "uuid": "",
        "name": "Acellories Inc.",
        "description": "Wholesalers of Mobile and Electronic Accessories",
        "website": "http://www.acellories.com",
        "categories": "Cell Phone Accessories / Wearables / Headphones / Speakers",
        "people": ["Albert Lalou"],
        "address": "5 Jules Ln",
        "city": "New Brunswick",
        "state": "NJ",
        "zipcode": "08901",
        "phoneNumber": "(718) 676-4677",
        "email": "",
        "createdAt": new Date(Date.now()),
        "updatedAt": new Date(Date.now()),
      },
      {
        "uuid": "",
        "name": "Acigi Relaxation/Dr. Fuji",
        "description": "Dr. Fuji massage chair series invite you to a dream world that will greatly enhance your health. It is designed to knead away and slacken the stiffness and fatigue using advanced knead balls and effective air bags. Dr. Fuji has succeeded in developing advanced, innovative massage technologies and idealizing synthetic treatments.",
        "website": "http://www.drfuji.com",
        "categories": "Wellness / Personal Care, General Merchandise, General Gifts, Furniture / Lamps / Lighting",
        "people": ["William Shen"],
        "address": "136-20, Roosevelt Ave #200B",
        "city": "Flushing",
        "state": "NY",
        "zipcode": "11354",
        "phoneNumber": "1 (510) 651-9088",
        "email": "service@drfuji.com",
        "createdAt": new Date(Date.now()),
        "updatedAt": new Date(Date.now()),
      },
      {
        "uuid": "",
        "name": "Adorable Pillows Mfg. Inc.",
        "description": "We are manufacture of pillows, comforters, mattress pads, mattress cover and pillow protectors. Most of our items are made in USA.",
        "website": "http://www.adorablepillows.com",
        "categories": "Bed / Bath, Interior Décor (Curtains/Wall Art/etc.), Outdoor Living / Décor",
        "people": ["Maria Galarza", "Felix Galarza"],
        "address": "902 Essex street",
        "city": "Brooklyn",
        "state": "NY",
        "zipcode": "11208",
        "phoneNumber": "(718) 272-1722",
        "email": "information@adorablepillows.com",
        "createdAt": new Date(Date.now()),
        "updatedAt": new Date(Date.now()),
      },
      {
        "uuid": "",
        "name": "Advance Apparels Inc.",
        "description": "Manufacturers & imporers of women's garments. Product categorgies include blouses, cover-ups, umbrella dresses, batik dresses, and tie-dye. With over 90% products being manufactured at our in-house facilities in India, our customers can expect high quality and lasting products. All products come in an assortment of 6+ colors and we offer very low order minimums.",
        "website": "http://www.advanceapparels.com",
        "categories": "Kids / Baby Apparel, Plus Size Apparel, Women's Apparel",
        "people": ["Akash Bajaj"],
        "address": "89 Leuning St Unit A2/A3",
        "city": "South Hackensack",
        "state": "NJ",
        "zipcode": "07606",
        "phoneNumber": "(212) 481-7246",
        "email": "sales@advanceapparels.com",
        "createdAt": new Date(Date.now()),
        "updatedAt": new Date(Date.now()),
      },
      {
        "uuid": "",
        "name": "Advanced Labeling Products Inc.",
        "description": "Advanced Labeling Products has built an outstanding reputation as a leading distributor of labels and bar-coding equipment for over Twenty Five Years. We offer a full line of printers with an extensive line of thermal transfer and direct thermal labels and ribbons. The printers range in size, speed and capability, for high to low volume computer driven printers. Advanced Labeling Products also offers a full line of price marking and date coding labelers and labels for all industries. To name a few brands, Contact, Garvey, Monarch and Towa. Advanced Labeling Products company philosophy is providing exceptional products and outstanding customer service at a competitive price. Let our friendly and knowledgeable sales professionals assist you in finding the right label and printer for your application. Make Advanced Labeling Products a single source for all your labeling ne",
        "website": "http://www.advancedlabelingproducts.com",
        "categories": "Logistics / Shipping, POS / Credit Card Services / Inventory Mgmt / Software, Store Displays / Fixturing / Signage / Packaging, General Merchandise, Office / School Supplies",
        "people": ["Bill O'Connor"],
        "address": "7704 Skyline Ct CA 91384",
        "city": "Castaic",
        "state": "CA",
        "zipcode": "91384",
        "phoneNumber": "(661) 424-1100",
        "email": "",
        "createdAt": new Date(Date.now()),
        "updatedAt": new Date(Date.now()),
      },
      {
        "uuid": "",
        "name": "Afnan Perfumes USA",
        "description": "AFNAN PERFUMES USA is a brand and a business, has showcased that is more than just perfumes: it is design, experience, expertise and more.\n\nAFNAN PERFUMES USA has provided essential memories for local and international markets, bringing to life key experiences through each design. Our designs reflect the unique and crafted experience our scents and packaging offer to the market as well as our heritage and unique quality.",
        "website": "https://www.afnanperfumesusa.com/",
        "categories": "Cosmetics / Nails / Hair Products, Fragrance / Perfume, Wellness / Personal Care, General Merchandise, General Gifts",
        "people": ["R. Meherali"],
        "address": "P.O. Box 7771, Jurf Ind. Area 1,",
        "city": "Ajman",
        "state": "U.A.E.",
        "zipcode": "",
        "phoneNumber": "971 6 747 4441",
        "email": "",
        "createdAt": new Date(Date.now()),
        "updatedAt": new Date(Date.now()),
      },
      {
        "uuid": "",
        "name": "AJ Western Wear and Leather Imports, Incorporation",
        "description": "Established 2006 in USA by My Beloved Father- Mr. Ashwani Kumar Shoor. Our Company has 18 Years of Experience in Manufacturing of Leather Garments, Leather Accessories and Textile Garments. AJ is a well-Established name in the industry. Our Products Successfully Wholesale to more than 2000 Stores Nationwide. We are Distributors of Premium Quality Western RODEO Shirts & Jackets for Men, Women and Kids. You will also find Western Rodeo Boots, Western Hats and Complete Head to Toe Western Outfit with us. We are Accredited by Better Business Bureau.\nOur Products are Made in India, Mexico and USA.\nWe also offer Private labeling and Drop Shipping Services.\nCome on Over for the Best Quality Product and Affordable Prices. God Bless !!",
        "website": "http://www.ajwsternwearleather.com",
        "categories": "Small Leather Goods (Belts/Wallets/etc), Men's Apparel, Men's Footwear, Women's Footwear, Made in the USA",
        "people": ["Arjun Shoor"],
        "address": "",
        "city": "",
        "state": "",
        "zipcode": "",
        "phoneNumber": "1(951)777-6670",
        "email": "",
        "createdAt": new Date(Date.now()),
        "updatedAt": new Date(Date.now()),
      },
      {
        "uuid": "",
        "name": "Ajmal Perfumes",
        "description": "Parfume",
        "website": "http://www.ajmalperfumeus.com",
        "categories": "Fragrance / Perfume, Wellness / Personal Care",
        "people": ["Safdar Hussain"],
        "address": "900 Grand Blvd.",
        "city": "Deer Park",
        "state": "NY",
        "zipcode": "11729",
        "phoneNumber": "1-800-PARFUMS (727-3867)",
        "email": "",
        "createdAt": new Date(Date.now()),
        "updatedAt": new Date(Date.now()),
      },
      {
        "uuid": "",
        "name": "Akzanwholesale.com",
        "description": "For over 30 years RNZ Imports LLC. DBA AkzanWholesale.com has been a leader in the manufacturing and distribution of millions of fashion time pieces. Our factory in Shenzhen, China has the capacity to produce millions of fashion watches yearly. We know what sells because we''ve seen the ups and downs of this industry. Our forecasting experience ensures that we always have the freshest merchandise before the trends hit. We aim to only bring in good product and we''ve set a standard that is hard to compete with at our price point.",
        "website": "http://www.akzanwholesale.com",
        "categories": "Fashion Jewelry / Watches, Travel Size / Over-the-Counter, General Merchandise, Promotional Products, Fine Jewelry / Watches (Diamonds/Gemstones/Gold)",
        "people": ["Irene Torres"],
        "address": "",
        "city": "",
        "state": "",
        "zipcode": "",
        "phoneNumber": "",
        "email": "",
        "createdAt": new Date(Date.now()),
        "updatedAt": new Date(Date.now()),
      },
      {
        "uuid": "",
        "name": "Al Haramain Perfumes",
        "description": "Al Haramain Perfumes has been a front-runner in perfumery since 1970. We do what we love and so we always explore the changing trends to consistently cater to the tastes of our discerning customers.",
        "website": "https://shop.alharamainperfumes.com/",
        "categories": "",
        "people": ["Prem Nair"],
        "address": "1242 S Hill Street",
        "city": "Los Angeles",
        "state": "CA",
        "zipcode": "90015",
        "phoneNumber": "213.746.8696",
        "email": "web@akzanwholesale.com",
        "createdAt": new Date(Date.now()),
        "updatedAt": new Date(Date.now()),
      },
      {
        "uuid": "",
        "name": "Al Hussein Perfumes Inc",
        "description": "We cater to all the ethnic groups of people throughout North & South America. We directly source from the manufacturer and cater to the basic to luxurious needs of our loyal customers. We have local offices in Minneapolis, Seattle, and New York to manage the entire USA operation and, our own trucking/routing system in place, to deliver to our customers in a timely and secure.",
        "website": "https://alhusseinperfumes.com/",
        "categories": "Fragrance / Perfume",
        "people": ["Hussein Isse", "Mohammed Rahman"],
        "address": "",
        "city": "Minneapolis",
        "state": "MN",
        "zipcode": "",
        "phoneNumber": "1 (612) 824-4237",
        "email": "Info@alhusseinperfumes.com",
        "createdAt": new Date(Date.now()),
        "updatedAt": new Date(Date.now()),
      },
      {
        "uuid": "",
        "name": "Albani Corp",
        "description": "",
        "website": "http://albaniperfumes.com",
        "categories": "Fragrance / Perfume",
        "people": ["Ali Ghandour"],
        "address": "1951 NW 93rd Ave",
        "city": "Miami",
        "state": "FL",
        "zipcode": "33172",
        "phoneNumber": "(305) 500-9838",
        "email": "info@albaniperfumes.com",
        "createdAt": new Date(Date.now()),
        "updatedAt": new Date(Date.now()),
      },
      {
        "uuid": "",
        "name": "Alef Standard Packaging Co",
        "description": "Since 1985, Alef Standard Packaging",
        "website": "http://www.alefpackaging.com",
        "categories": "Closeouts / Liquidation, Stationery / Party / Paper / Gift Wrap, Christmas",
        "people": ["Scott Rosenthal"],
        "address": "12300 McNulty Rd",
        "city": "Philadelphia",
        "state": "PA",
        "zipcode": "19154",
        "phoneNumber": "(800) 322-2533, (215) 203-0200",
        "email": "support@alefpackaging.com",
        "createdAt": new Date(Date.now()),
        "updatedAt": new Date(Date.now()),
      },
      {
        "uuid": "",
        "name": "Alfa Bags",
        "description": "A.L.F.A. - A LADY FASHION ACCESSIORIES\nALFA is 33 years U.S.A. company to offer women's handbags, travel bags, giveaway bags in States and Oversea for your boutique shops, wholesales distributions, chain retails, and custom events. We develop our variety styles in Los Angeles, California. To provide unique styles and designs concept to fit your needs, we have strong design team working with your every important custom project. We have 2 warehouses located at California and Oklahoma for your convenience that provide the fast and low cost shipping for today business.",
        "website": "https://alfatravelgear.com/",
        "categories": "Handbags, Dollar Store Items, Souvenirs, Luggage / Travel Accessories, Pet Products",
        "people": ["Tony Y Ho"],
        "address": "",
        "city": "",
        "state": "",
        "zipcode": "",
        "phoneNumber": "1(626)941-3498  1(866)864-9299",
        "email": "",
        "createdAt": new Date(Date.now()),
        "updatedAt": new Date(Date.now()),
      },
      {
        "uuid": "",
        "name": "All-Link Household Inc.",
        "description": "Our company provides different cleaning products for consumer and business.",
        "website": "https://www.jesun.com",
        "categories": "General Merchandise, Personal Protective Equipment / Health + Safety Essentials",
        "people": ["Olivia Zhang"],
        "address": "1555 S Dupont Ave Ste D",
        "city": "Ontario",
        "state": "CA",
        "zipcode": "91761",
        "phoneNumber": "(802) 689-2836",
        "email": "",
        "createdAt": new Date(Date.now()),
        "updatedAt": new Date(Date.now()),
      },
      {
        "uuid": "",
        "name": "Allary Corporation",
        "description": "Allary Corporation is #1 supplier of Value Sewing, Scissors (8 categories), Craft and Hobby, and Shoe and Foot Care items. Freight is prepaid on orders of $1,000 and more. All categories can be combined to meet the minimum for Prepaid Freight. Offices in Union, NJ, Springfield, MO and Hong Kong. Allary is diversified in suppling customer''''s private brand. Three versatile programs to meet customer needs. Shipping options are FOB Asia, Port of Entry and Domestic.",
        "website": "http://www.allarycorp.com",
        "categories": "Travel Size / Over-the-Counter, Dollar Store Items, General Merchandise, Art / Craft / Hobby, Office / School Supplies",
        "people": ["Larry Self"],
        "address": "2204 Morris Avenue #209",
        "city": "Union",
        "state": "NJ",
        "zipcode": "07083",
        "phoneNumber": "800-253-1440",
        "email": "allary@allarycorp.com  info@allarycorp.com",
        "createdAt": new Date(Date.now()),
        "updatedAt": new Date(Date.now()),
      },
      {
        "uuid": "",
        "name": "Allen Company",
        "description": "The ALLEN company has been a pround maker of \"Made in the USA\" products for 49 years. Over the years we have expanded our production and are proud to be one of the largest makers of Hunting, Fishing, and Outdoor products in the US. Due to demands of our customers in categories, we do source globally, but our line up of \"Made in the USA\" products is endless, and a key ingredient to our heritage. Our Grill /Outdoor Patio covers take on its own branding under Modern Leisure with Moterey and Chalet branding. This along with our \"Love Laugh Craft\" brand of craft supplies offers a wide spectrum of product categories under one roof",
        "website": "http://www.byallen.com",
        "categories": "General Merchandise, Outdoor Living / Décor, Made in the USA, Camping / Outdoor Recreation, Sporting Goods",
        "people": ["Greg Stawczyk"],
        "address": "609 South 104th Street",
        "city": "Louisville",
        "state": "CO",
        "zipcode": "80027",
        "phoneNumber": "",
        "email": "ConsumerService@allencompany.net",
        "createdAt": new Date(Date.now()),
        "updatedAt": new Date(Date.now()),
      },
      {
        "uuid": "",
        "name": "Almar Sales Company",
        "description": "ALMAR SALES COMPANY IS AN INTERNATIONAL CONSUMER PRODUCTS MANUFACTURER AND SUPPLIER OF FACHIONABLE ACCESSORY PRODUCTS AND COSMETICS FOR OVER 45 YRS. ALMAR SPECIALIZES IN DESIGINING, MANUFACTURING AND DISTRIBUTING FASHION HAIR ACC, COSTUME JEWELRY, COSMETICS, CHILDREN''''S TOYS AND NOVELTY ITEMS. ALMARS PRODUCTS LINE OFFERS SOMETHING FOR EVERY AGE GROUP AND WILL EXCITE YOUR CUSTOMERS WHILE OFFERING THE LATEST FASHION BASIC VALUE MERCHANDISE.",
        "website": "http://www.almarsales.com",
        "categories": "Cosmetics / Nails / Hair Products, Dollar Store Items, Novelties (Humor/Gags & Pranks/Drinking Accessories/etc)",
        "people": ["Jimmy Assis"],
        "address": "",
        "city": "",
        "state": "",
        "zipcode": "",
        "phoneNumber": "212.594.6920 x 1340",
        "email": "help@almarsales.com.",
        "createdAt": new Date(Date.now()),
        "updatedAt": new Date(Date.now()),
      },
      {
        "uuid": "",
        "name": "Almas National Company For Perfumes",
        "description": "",
        "website": "https://ghalati.com/",
        "categories": "",
        "people": ["Amr Elbadawy", "Mokhtar Khashafa"],
        "address": "",
        "city": "",
        "state": "",
        "zipcode": "",
        "phoneNumber": "9 665 452 89354",
        "email": "support@ghalati.com",
        "createdAt": new Date(Date.now()),
        "updatedAt": new Date(Date.now()),
      }
    ];
    data.forEach(item => {
      item.uuid = uuidv4().toString();
    });
    return await queryInterface.bulkInsert("Vendors", data, {});
  },
  
  // eslint-disable-next-line
  async down (queryInterface: QueryInterface, Sequelize: typeof DataTypes) {
    return await queryInterface.bulkDelete("Vendors", {}, {});
  }
};
