import {DataTypes, QueryInterface} from "sequelize";

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  // eslint-disable-next-line
  async up (queryInterface: QueryInterface, Sequelize: typeof DataTypes) {
        return await queryInterface.bulkInsert("Categories", [{
            parentcategory: "Accessories",
            subcategory: "Fashion Jewelry / Watches",
            createdAt: new Date(Date.now()),
            updatedAt: new Date(Date.now()),
        },
        {
            parentcategory: "Accessories",
            subcategory: "Handbags",
            createdAt: new Date(Date.now()),
            updatedAt: new Date(Date.now()),
        },
        {
            parentcategory: "Accessories",
            subcategory: "Hats / Scarves",
            createdAt: new Date(Date.now()),
            updatedAt: new Date(Date.now()),
        },
        {
            parentcategory: "Accessories",
            subcategory: "Small Leather Goods (Belts/Wallets/etc)",
            createdAt: new Date(Date.now()),
            updatedAt: new Date(Date.now()),
        },
        {
            parentcategory: "Accessories",
            subcategory: "Sunglasses / Eyewear",
            createdAt: new Date(Date.now()),
            updatedAt: new Date(Date.now()),
        },
        {
            parentcategory: "Alternative / Lifestyle Products",
            subcategory: "Adult Novelty",
            createdAt: new Date(Date.now()),
            updatedAt: new Date(Date.now()),
        },
        {
            parentcategory: "Alternative / Lifestyle Products",
            subcategory: "CBD or other Cannabinoids",
            createdAt: new Date(Date.now()),
            updatedAt: new Date(Date.now()),
        },
        {
            parentcategory: "Alternative / Lifestyle Products",
            subcategory: "Hemp",
            createdAt: new Date(Date.now()),
            updatedAt: new Date(Date.now()),
        },
        {
            parentcategory: "Alternative / Lifestyle Products",
            subcategory: "Kratom",
            createdAt: new Date(Date.now()),
            updatedAt: new Date(Date.now()),
        },
        {
            parentcategory: "Alternative / Lifestyle Products",
            subcategory: "Smoke Accessories",
            createdAt: new Date(Date.now()),
            updatedAt: new Date(Date.now()),
        },
        {
            parentcategory: "Alternative / Lifestyle Products",
            subcategory: "Vape",
            createdAt: new Date(Date.now()),
            updatedAt: new Date(Date.now()),
        },
        {
            parentcategory: "Apparel",
            subcategory: "Kids / Baby Apparel",
            createdAt: new Date(Date.now()),
            updatedAt: new Date(Date.now()),
        },
        {
            parentcategory: "Apparel",
            subcategory: "Men's Apparel",
            createdAt: new Date(Date.now()),
            updatedAt: new Date(Date.now()),
        },
        {
            parentcategory: "Apparel",
            subcategory: "Plus Size Apparel",
            createdAt: new Date(Date.now()),
            updatedAt: new Date(Date.now()),
        },
        {
            parentcategory: "Apparel",
            subcategory: "Swimwear",
            createdAt: new Date(Date.now()),
            updatedAt: new Date(Date.now()),
        },
        {
            parentcategory: "Apparel",
            subcategory: "Undergarments / Hosiery / Socks",
            createdAt: new Date(Date.now()),
            updatedAt: new Date(Date.now()),
        },
        {
            parentcategory: "Apparel",
            subcategory: "Women's Apparel",
            createdAt: new Date(Date.now()),
            updatedAt: new Date(Date.now()),
        },
        {
            parentcategory: "Baby & Kids Products",
            subcategory: "Baby / Kids Products",
            createdAt: new Date(Date.now()),
            updatedAt: new Date(Date.now()),
        },
        {
            parentcategory: "Beauty & Wellness",
            subcategory: "Cosmetics / Nails / Hair Products",
            createdAt: new Date(Date.now()),
            updatedAt: new Date(Date.now()),
        },
        {
            parentcategory: "Beauty & Wellness",
            subcategory: "Fragrance / Perfume",
            createdAt: new Date(Date.now()),
            updatedAt: new Date(Date.now()),
        },
        {
            parentcategory: "Beauty & Wellness",
            subcategory: "Wellness / Personal Care",
            createdAt: new Date(Date.now()),
            updatedAt: new Date(Date.now()),
        },
        {
            parentcategory: "Books & Publications",
            subcategory: "Books / Publications",
            createdAt: new Date(Date.now()),
            updatedAt: new Date(Date.now()),
        },
        {
            parentcategory: "Business Service Solutions",
            subcategory: "Logistics / Shipping",
            createdAt: new Date(Date.now()),
            updatedAt: new Date(Date.now()),
        },
        {
            parentcategory: "Business Service Solutions",
            subcategory: "Marketing / Web / Social Media",
            createdAt: new Date(Date.now()),
            updatedAt: new Date(Date.now()),
        },
        {
            parentcategory: "Business Service Solutions",
            subcategory: "POS / Credit Card Services / Inventory Mgmt / Software",
            createdAt: new Date(Date.now()),
            updatedAt: new Date(Date.now()),
        },
        {
            parentcategory: "Business Service Solutions",
            subcategory: "Store Displays / Fixturing / Signage / Packaging",
            createdAt: new Date(Date.now()),
            updatedAt: new Date(Date.now()),
        },
        {
            parentcategory: "Convenience Store",
            subcategory: "Herbal Supplements",
            createdAt: new Date(Date.now()),
            updatedAt: new Date(Date.now()),
        },
        {
            parentcategory: "Convenience Store",
            subcategory: "Snacks / Candy / Energy / Drinks",
            createdAt: new Date(Date.now()),
            updatedAt: new Date(Date.now()),
        },
        {
            parentcategory: "Convenience Store",
            subcategory: "Travel Size / Over-the-Counter",
            createdAt: new Date(Date.now()),
            updatedAt: new Date(Date.now()),
        },
        {
            parentcategory: "Electronics",
            subcategory: "Cameras / Tablets / Drones / MP3 Players / Home / Entertainment Audio etc.",
            createdAt: new Date(Date.now()),
            updatedAt: new Date(Date.now()),
        },
        {
            parentcategory: "Electronics",
            subcategory: "Cell Phone Accessories / Wearables / Headphones / Speakers",
            createdAt: new Date(Date.now()),
            updatedAt: new Date(Date.now()),
        },
        {
            parentcategory: "Footwear",
            subcategory: "Kids / Baby Footwear",
            createdAt: new Date(Date.now()),
            updatedAt: new Date(Date.now()),
        },
        {
            parentcategory: "Footwear",
            subcategory: "Men's Footwear",
            createdAt: new Date(Date.now()),
            updatedAt: new Date(Date.now()),
        },
        {
            parentcategory: "Footwear",
            subcategory: "Women's Footwear",
            createdAt: new Date(Date.now()),
            updatedAt: new Date(Date.now()),
        },
        {
            parentcategory: "General Merchandise",
            subcategory: "Automotive",
            createdAt: new Date(Date.now()),
            updatedAt: new Date(Date.now()),
        },
        {
            parentcategory: "General Merchandise",
            subcategory: "Closeouts / Liquidation",
            createdAt: new Date(Date.now()),
            updatedAt: new Date(Date.now()),
        },
        {
            parentcategory: "General Merchandise",
            subcategory: "Dollar Store Items",
            createdAt: new Date(Date.now()),
            updatedAt: new Date(Date.now()),
        },
        {
            parentcategory: "General Merchandise",
            subcategory: "General Merchandise",
            createdAt: new Date(Date.now()),
            updatedAt: new Date(Date.now()),
        },
        {
            parentcategory: "Gift",
            subcategory: "Art / Craft / Hobby",
            createdAt: new Date(Date.now()),
            updatedAt: new Date(Date.now()),
        },
        {
            parentcategory: "Gift",
            subcategory: "General Gifts",
            createdAt: new Date(Date.now()),
            updatedAt: new Date(Date.now()),
        },
        {
            parentcategory: "Gift",
            subcategory: "Keepsakes / Collectibles",
            createdAt: new Date(Date.now()),
            updatedAt: new Date(Date.now()),
        },
        {
            parentcategory: "Gift",
            subcategory: "Promotional Products",
            createdAt: new Date(Date.now()),
            updatedAt: new Date(Date.now()),
        },
        {
            parentcategory: "Gift",
            subcategory: "Religious / Spiritual",
            createdAt: new Date(Date.now()),
            updatedAt: new Date(Date.now()),
        },
        {
            parentcategory: "Gift",
            subcategory: "Souvenirs",
            createdAt: new Date(Date.now()),
            updatedAt: new Date(Date.now()),
        },
        {
            parentcategory: "Gift",
            subcategory: "Stationery / Party / Paper / Gift Wrap",
            createdAt: new Date(Date.now()),
            updatedAt: new Date(Date.now()),
        },
        {
            parentcategory: "Gift",
            subcategory: "Wedding / Bridal",
            createdAt: new Date(Date.now()),
            updatedAt: new Date(Date.now()),
        },
        {
            parentcategory: "Handmade",
            subcategory: "Handmade",
            createdAt: new Date(Date.now()),
            updatedAt: new Date(Date.now()),
        },
        {
            parentcategory: "Home Accents",
            subcategory: "Bed / Bath",
            createdAt: new Date(Date.now()),
            updatedAt: new Date(Date.now()),
        },
        {
            parentcategory: "Home Accents",
            subcategory: "Floral / Floral Supplies",
            createdAt: new Date(Date.now()),
            updatedAt: new Date(Date.now()),
        },
        {
            parentcategory: "Home Accents",
            subcategory: "Furniture / Lamps / Lighting",
            createdAt: new Date(Date.now()),
            updatedAt: new Date(Date.now()),
        },
        {
            parentcategory: "Home Accents",
            subcategory: "Interior Décor (Curtains/Wall Art/etc.)",
            createdAt: new Date(Date.now()),
            updatedAt: new Date(Date.now()),
        },
        {
            parentcategory: "Home Accents",
            subcategory: "Kitchen / Tabletop / Cookware / Cutlery / Small Appliances",
            createdAt: new Date(Date.now()),
            updatedAt: new Date(Date.now()),
        },
        {
            parentcategory: "Home Accents",
            subcategory: "Outdoor Living / Décor",
            createdAt: new Date(Date.now()),
            updatedAt: new Date(Date.now()),
        },
        {
            parentcategory: "Home Improvement",
            subcategory: "Hardware / Tools",
            createdAt: new Date(Date.now()),
            updatedAt: new Date(Date.now()),
        },
        {
            parentcategory: "Jewelry",
            subcategory: "Body Piercings",
            createdAt: new Date(Date.now()),
            updatedAt: new Date(Date.now()),
        },
        {
            parentcategory: "Jewelry",
            subcategory: "Fine Jewelry / Watches (Diamonds/Gemstones/Gold)",
            createdAt: new Date(Date.now()),
            updatedAt: new Date(Date.now()),
        },
        {
            parentcategory: "Jewelry",
            subcategory: "Silver / Semi Precious",
            createdAt: new Date(Date.now()),
            updatedAt: new Date(Date.now()),
        },
        {
            parentcategory: "Licensed Merchandise",
            subcategory: "Characters / Brands / Entertainment",
            createdAt: new Date(Date.now()),
            updatedAt: new Date(Date.now()),
        },
        {
            parentcategory: "Licensed Merchandise",
            subcategory: "Collegiate / Major League Sports",
            createdAt: new Date(Date.now()),
            updatedAt: new Date(Date.now()),
        },
        {
            parentcategory: "Luggage & Travel Accessories",
            subcategory: "Luggage / Travel Accessories",
            createdAt: new Date(Date.now()),
            updatedAt: new Date(Date.now()),
        },
        {
            parentcategory: "Made in the USA",
            subcategory: "Made in the USA",
            createdAt: new Date(Date.now()),
            updatedAt: new Date(Date.now()),
        },
        {
            parentcategory: "Office & School Supplies",
            subcategory: "Office / School Supplies",
            createdAt: new Date(Date.now()),
            updatedAt: new Date(Date.now()),
        },
        {
            parentcategory: "Outdoor Recreation & Tactical",
            subcategory: "Camping / Outdoor Recreation",
            createdAt: new Date(Date.now()),
            updatedAt: new Date(Date.now()),
        },
        {
            parentcategory: "Outdoor Recreation & Tactical",
            subcategory: "Personal Security / Tactical",
            createdAt: new Date(Date.now()),
            updatedAt: new Date(Date.now()),
        },
        {
            parentcategory: "Outdoor Recreation & Tactical",
            subcategory: "Sporting Goods",
            createdAt: new Date(Date.now()),
            updatedAt: new Date(Date.now()),
        },
        {
            parentcategory: "Personal Protective Equipment / Health & Safety Essentials",
            subcategory: "Personal Protective Equipment / Health + Safety Essentials",
            createdAt: new Date(Date.now()),
            updatedAt: new Date(Date.now()),
        },
        {
            parentcategory: "Pet Products",
            subcategory: "Pet Products",
            createdAt: new Date(Date.now()),
            updatedAt: new Date(Date.now()),
        },
        {
            parentcategory: "Seasonal",
            subcategory: "Christmas",
            createdAt: new Date(Date.now()),
            updatedAt: new Date(Date.now()),
        },
        {
            parentcategory: "Seasonal",
            subcategory: "Halloween",
            createdAt: new Date(Date.now()),
            updatedAt: new Date(Date.now()),
        },
        {
            parentcategory: "Seasonal",
            subcategory: "Other Holiday",
            createdAt: new Date(Date.now()),
            updatedAt: new Date(Date.now()),
        },
        {
            parentcategory: "Toys & Novelties",
            subcategory: "Games / Puzzles",
            createdAt: new Date(Date.now()),
            updatedAt: new Date(Date.now()),
        },
        {
            parentcategory: "Toys & Novelties",
            subcategory: "Novelties (Humor/Gags & Pranks/Drinking Accessories/etc)",
            createdAt: new Date(Date.now()),
            updatedAt: new Date(Date.now()),
        },
        {
            parentcategory: "Toys & Novelties",
            subcategory: "Plush",
            createdAt: new Date(Date.now()),
            updatedAt: new Date(Date.now()),
        },
        {
            parentcategory: "Toys & Novelties",
            subcategory: "Toys / Figures",
            createdAt: new Date(Date.now()),
            updatedAt: new Date(Date.now()),
        }], {});
    },
  // eslint-disable-next-line
  async down (queryInterface: QueryInterface, Sequelize: typeof DataTypes) {
        return await queryInterface.bulkDelete("Categories", {}, {});
    },
};
